version: '3'
services:
  nginx:
    container_name: nginx-with-grpc
    image: nginx:1.13.10
    restart: always
    ports:
    - 80:80
    - 443:443    
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d     
    - ./nginx/logs:/etc/nginx/logs       

  movie:
    depends_on:  
      - nginx  
    container_name: movie
    build: ./movies
    hostname: movie
    restart: always   
    ports:
      - 6565:6565        